<template>
  <p>Switch组件</p>
   <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p> 
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
    <p>Switch 的文档</p>
</template>

<script lang="ts">
export default {};
</script>

<style></style>
